### ISSUE TITLE
Twitter::Error::NotFound when running bot

### ISSUE THREAD

**Issue by LunarLoony** [vexorian/twitter-image-bot#1]
I'm trying to run this bot from a Raspberry Pi running Buster. I've run testcontent.rb and it seems happy with my pictures array, but actually running the bot (`ruby run.rb --ignore-schedule`) outputs the following:

```
Will ignore schedule.
@invaders_bot: User information updated
@invaders_bot: 8 minutes since latest tweet.
@invaders_bot: starting tweet stream
@invaders_bot: Twitter::Error::NotFound
	/var/lib/gems/2.5.0/gems/twitter-5.17.0/lib/twitter/streaming/response.rb:21:in on_headers_complete'
	/var/lib/gems/2.5.0/gems/twitter-5.17.0/lib/twitter/streaming/response.rb:16:in `<<'
	/var/lib/gems/2.5.0/gems/twitter-5.17.0/lib/twitter/streaming/response.rb:16:in `<<'
	/var/lib/gems/2.5.0/gems/twitter-5.17.0/lib/twitter/streaming/connection.rb:22:in `stream'
	/var/lib/gems/2.5.0/gems/twitter-5.17.0/lib/twitter/streaming/client.rb:119:in `request'
	/var/lib/gems/2.5.0/gems/twitter-5.17.0/lib/twitter/streaming/client.rb:92:in `user'
	/var/lib/gems/2.5.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/bot.rb:362:in `start'
	run.rb:39:in `block (3 levels) in <main>'
	run.rb:37:in `loop'
	run.rb:37:in `block (2 levels) in <main>'
@invaders_bot: Sleeping before reconnect
```

So, as such, the bot won't tweet anything. Except sometimes it does, and there doesn't seem to be a pattern - none that I can see anyway.

Sorry if this is too general a query - I'm totally new to Ruby, so diagnosing this has been a little difficult.

**Comment by vexorian** [comment]
Well, from what I understand, a year ago, twitter disabled the streaming api and the ability to listen to notifcations. I didn't really reserve time to check into how this affects my bots because they seem to still be working... So my guess is that this error does appear in the logs, but all it means is that the bot cannot subscribe to notifications/tweet feed. My bots used to be able to follow you and react to stuff you type in the feed, but they can't do that anymore.

So I think that's what the error means, that those features can't be initialized.  But the other features such as posting tweets should still work (and they still do with all my currently active bots, at least) And you say that your bot is working, so I don't think the issue is caused by this error message. Look for some other errors in the logs.


To help you debug:

- Make sure you have your twitter user name (yours) as BOT_OWNER in botconfig.rb
- Make sure your bot is configured as TWITTER_USERNAME
- Now that you have this set up, you can actually order your bot to post something by sending them a direct message that starts with the text "!tweet " (without quotes). So try finding a way to look to the logs at the same time as you send this direct message, this way you can see exactly what's happening inside your bot when it is supposed to be tweeting.

**Comment by LunarLoony** [comment]
Right - that makes sense. What happened was, I assumed the bot would just tweet as soon as run.rb was executed, as opposed to just having it running all the time. The Twitter error was a red herring. My mistake...goes to show my lack of experience with Ruby, I guess.

Thanks anyway, think it might be worth tracking down the offending code and commenting it out.
